### ISSUE TITLE
Batch predictions

### ISSUE THREAD

**Issue by adamontherun** [fgarcialainez/ML4iOS#1]
Hi,
I wasn't able to find support for batch predictions https://bigml.com/developers/batch_predictions in your code. Is this something you support that I'm missing, or a feature you haven't implemented?

Thank you for putting this library together, great resource!
adam

**Comment by fgarcialainez** [comment]
Hi Adam,

First of all thanks for using ML4iOS. The case is that batch predictions are not available in the current version, in the same way than other nice features added recently in the platform. I apologize for that, but right now I am focused in other "side projects" like learning Swift or playing with other "advanced" Cocoa Touch Frameworks. Of any way I will add Batch Predictions and other cool stuff when I have the time (I will let you know).

Regards
